package secure

import (
	"crypto/rand"
	"encoding/base64"
	"fmt"
	"golang.org/x/crypto/scrypt"
)

// scrypt params.
const (
	n       = 1 << 15
	r       = 8
	p       = 1
	keyLen  = 32
	saltLen = 32
)

// HashPassword hashes password using "scrypt" with salt, generated by "crypto/rand" library.
// Also, it encodes hash to readable format using Base64.
// Returns hash, salt and an error.
func HashPassword(password []byte) (hash string, salt string, err error) {
	//gen salt
	saltBytes := make([]byte, saltLen)
	_, err = rand.Read(saltBytes)
	if err != nil {
		return "", "", fmt.Errorf("unable to generate salt: %w", err)
	}

	//hash password
	hashBytes, err := scrypt.Key(password, saltBytes, n, r, p, keyLen)
	if err != nil {
		return "", "", fmt.Errorf("unable to hash password: %w", err)
	}

	//make password hash readable
	hash = base64.StdEncoding.EncodeToString(hashBytes)
	salt = base64.StdEncoding.EncodeToString(saltBytes)
	return hash, salt, nil
}

func HashPasswordWithSalt(password []byte, salt string) (string, error) {
	saltBytes, err := base64.StdEncoding.DecodeString(salt)
	if err != nil {
		return "", fmt.Errorf("unable to decode salt: %w", err)
	}

	//hash password
	hashBytes, err := scrypt.Key(password, saltBytes, n, r, p, keyLen)
	if err != nil {
		return "", fmt.Errorf("unable to hash password: %w", err)
	}

	//make password hash readable
	hash := base64.StdEncoding.EncodeToString(hashBytes)
	return hash, nil
}
